# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'robot_gui.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QSlider, QSpacerItem, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(829, 772)
        MainWindow.setMinimumSize(QSize(829, 772))
        MainWindow.setMaximumSize(QSize(829, 772))
        font = QFont()
        font.setFamilies([u"Yu Gothic"])
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.Computer))
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setAutoFillBackground(False)
        self.frame_socket_configuration = QFrame(self.centralwidget)
        self.frame_socket_configuration.setObjectName(u"frame_socket_configuration")
        self.frame_socket_configuration.setGeometry(QRect(310, 10, 491, 71))
        self.frame_socket_configuration.setFrameShape(QFrame.Shape.Box)
        self.frame_socket_configuration.setFrameShadow(QFrame.Shadow.Plain)
        self.frame_socket_configuration.setLineWidth(2)
        self.label_socket_configuration = QLabel(self.frame_socket_configuration)
        self.label_socket_configuration.setObjectName(u"label_socket_configuration")
        self.label_socket_configuration.setGeometry(QRect(10, 10, 251, 21))
        font1 = QFont()
        font1.setFamilies([u"Yu Gothic"])
        font1.setPointSize(12)
        font1.setBold(True)
        self.label_socket_configuration.setFont(font1)
        self.IP_value = QLineEdit(self.frame_socket_configuration)
        self.IP_value.setObjectName(u"IP_value")
        self.IP_value.setGeometry(QRect(30, 40, 131, 22))
        self.IP_value.setMaxLength(15)
        self.IP_value.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.IP_value.setReadOnly(True)
        self.label_13 = QLabel(self.frame_socket_configuration)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 40, 31, 21))
        self.label_14 = QLabel(self.frame_socket_configuration)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(170, 40, 41, 21))
        self.Port_value = QLineEdit(self.frame_socket_configuration)
        self.Port_value.setObjectName(u"Port_value")
        self.Port_value.setGeometry(QRect(210, 40, 61, 22))
        self.Port_value.setMaxLength(5)
        self.Port_value.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.Port_value.setReadOnly(True)
        self.btn_set_socket = QPushButton(self.frame_socket_configuration)
        self.btn_set_socket.setObjectName(u"btn_set_socket")
        self.btn_set_socket.setGeometry(QRect(300, 40, 75, 24))
        self.btn_set_socket.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_reset_socket = QPushButton(self.frame_socket_configuration)
        self.btn_reset_socket.setObjectName(u"btn_reset_socket")
        self.btn_reset_socket.setGeometry(QRect(390, 40, 75, 24))
        self.btn_reset_socket.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(10, 70, 811, 691))
        self.tabWidget.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.tabWidget.setMouseTracking(True)
        self.tab_XYZ = QWidget()
        self.tab_XYZ.setObjectName(u"tab_XYZ")
        self.frame_tool_position = QFrame(self.tab_XYZ)
        self.frame_tool_position.setObjectName(u"frame_tool_position")
        self.frame_tool_position.setGeometry(QRect(300, 450, 491, 201))
        self.frame_tool_position.setFrameShape(QFrame.Shape.Box)
        self.frame_tool_position.setFrameShadow(QFrame.Shadow.Plain)
        self.frame_tool_position.setLineWidth(2)
        self.frame_tool_position.setMidLineWidth(0)
        self.label_tool_position = QLabel(self.frame_tool_position)
        self.label_tool_position.setObjectName(u"label_tool_position")
        self.label_tool_position.setGeometry(QRect(10, 10, 251, 20))
        self.label_tool_position.setFont(font1)
        self.layoutWidget = QWidget(self.frame_tool_position)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(20, 40, 451, 141))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_9 = QLabel(self.layoutWidget)
        self.label_9.setObjectName(u"label_9")

        self.gridLayout.addWidget(self.label_9, 0, 4, 1, 1)

        self.horizontalSpacer = QSpacerItem(13, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer, 0, 3, 1, 1)

        self.label_8 = QLabel(self.layoutWidget)
        self.label_8.setObjectName(u"label_8")

        self.gridLayout.addWidget(self.label_8, 2, 6, 1, 1)

        self.label_5 = QLabel(self.layoutWidget)
        self.label_5.setObjectName(u"label_5")

        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)

        self.lineEdit_RY = QLineEdit(self.layoutWidget)
        self.lineEdit_RY.setObjectName(u"lineEdit_RY")
        self.lineEdit_RY.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_RY.setReadOnly(True)

        self.gridLayout.addWidget(self.lineEdit_RY, 1, 5, 1, 1)

        self.label_7 = QLabel(self.layoutWidget)
        self.label_7.setObjectName(u"label_7")

        self.gridLayout.addWidget(self.label_7, 0, 6, 1, 1)

        self.label_4 = QLabel(self.layoutWidget)
        self.label_4.setObjectName(u"label_4")

        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)

        self.label = QLabel(self.layoutWidget)
        self.label.setObjectName(u"label")

        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.lineEdit_X = QLineEdit(self.layoutWidget)
        self.lineEdit_X.setObjectName(u"lineEdit_X")
        self.lineEdit_X.setCursorPosition(3)
        self.lineEdit_X.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_X.setReadOnly(True)

        self.gridLayout.addWidget(self.lineEdit_X, 0, 1, 1, 1)

        self.label_12 = QLabel(self.layoutWidget)
        self.label_12.setObjectName(u"label_12")

        self.gridLayout.addWidget(self.label_12, 1, 6, 1, 1)

        self.lineEdit_RZ = QLineEdit(self.layoutWidget)
        self.lineEdit_RZ.setObjectName(u"lineEdit_RZ")
        self.lineEdit_RZ.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_RZ.setReadOnly(True)

        self.gridLayout.addWidget(self.lineEdit_RZ, 2, 5, 1, 1)

        self.lineEdit_Z = QLineEdit(self.layoutWidget)
        self.lineEdit_Z.setObjectName(u"lineEdit_Z")
        self.lineEdit_Z.setEnabled(True)
        self.lineEdit_Z.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_Z.setReadOnly(True)

        self.gridLayout.addWidget(self.lineEdit_Z, 2, 1, 1, 1)

        self.lineEdit_RX = QLineEdit(self.layoutWidget)
        self.lineEdit_RX.setObjectName(u"lineEdit_RX")
        self.lineEdit_RX.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_RX.setReadOnly(True)

        self.gridLayout.addWidget(self.lineEdit_RX, 0, 5, 1, 1)

        self.lineEdit_Y = QLineEdit(self.layoutWidget)
        self.lineEdit_Y.setObjectName(u"lineEdit_Y")
        self.lineEdit_Y.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_Y.setReadOnly(True)

        self.gridLayout.addWidget(self.lineEdit_Y, 1, 1, 1, 1)

        self.label_10 = QLabel(self.layoutWidget)
        self.label_10.setObjectName(u"label_10")

        self.gridLayout.addWidget(self.label_10, 1, 4, 1, 1)

        self.label_3 = QLabel(self.layoutWidget)
        self.label_3.setObjectName(u"label_3")

        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)

        self.label_6 = QLabel(self.layoutWidget)
        self.label_6.setObjectName(u"label_6")

        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)

        self.label_2 = QLabel(self.layoutWidget)
        self.label_2.setObjectName(u"label_2")

        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)

        self.label_11 = QLabel(self.layoutWidget)
        self.label_11.setObjectName(u"label_11")

        self.gridLayout.addWidget(self.label_11, 2, 4, 1, 1)

        self.frame_axis_direction = QFrame(self.tab_XYZ)
        self.frame_axis_direction.setObjectName(u"frame_axis_direction")
        self.frame_axis_direction.setGeometry(QRect(300, 10, 491, 421))
        self.frame_axis_direction.setFrameShape(QFrame.Shape.Box)
        self.frame_axis_direction.setFrameShadow(QFrame.Shadow.Plain)
        self.frame_axis_direction.setLineWidth(2)
        self.frame_axis_direction.setMidLineWidth(0)
        self.label_axis_picture = QLabel(self.frame_axis_direction)
        self.label_axis_picture.setObjectName(u"label_axis_picture")
        self.label_axis_picture.setGeometry(QRect(10, 10, 251, 20))
        self.label_axis_picture.setFont(font1)
        self.axis_picture = QLabel(self.frame_axis_direction)
        self.axis_picture.setObjectName(u"axis_picture")
        self.axis_picture.setGeometry(QRect(10, 60, 471, 331))
        self.axis_picture.setPixmap(QPixmap(u"rcc/axis_png.png"))
        self.axis_picture.setScaledContents(True)
        self.frame_tcp_orientation = QFrame(self.tab_XYZ)
        self.frame_tcp_orientation.setObjectName(u"frame_tcp_orientation")
        self.frame_tcp_orientation.setGeometry(QRect(10, 340, 271, 311))
        self.frame_tcp_orientation.setFrameShape(QFrame.Shape.Box)
        self.frame_tcp_orientation.setFrameShadow(QFrame.Shadow.Plain)
        self.frame_tcp_orientation.setLineWidth(2)
        self.frame_tcp_orientation.setMidLineWidth(0)
        self.btn_RYm = QPushButton(self.frame_tcp_orientation)
        self.btn_RYm.setObjectName(u"btn_RYm")
        self.btn_RYm.setGeometry(QRect(100, 180, 71, 61))
        font2 = QFont()
        font2.setFamilies([u"Yu Gothic"])
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setUnderline(False)
        self.btn_RYm.setFont(font2)
        self.btn_RYm.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label_tcp_orientation = QLabel(self.frame_tcp_orientation)
        self.label_tcp_orientation.setObjectName(u"label_tcp_orientation")
        self.label_tcp_orientation.setGeometry(QRect(10, 10, 251, 20))
        self.label_tcp_orientation.setFont(font1)
        self.btn_RYp = QPushButton(self.frame_tcp_orientation)
        self.btn_RYp.setObjectName(u"btn_RYp")
        self.btn_RYp.setGeometry(QRect(100, 100, 71, 61))
        font3 = QFont()
        font3.setFamilies([u"Yu Gothic"])
        font3.setPointSize(12)
        font3.setBold(True)
        font3.setItalic(False)
        font3.setUnderline(False)
        font3.setStrikeOut(False)
        font3.setKerning(True)
        self.btn_RYp.setFont(font3)
        self.btn_RYp.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_RXp = QPushButton(self.frame_tcp_orientation)
        self.btn_RXp.setObjectName(u"btn_RXp")
        self.btn_RXp.setGeometry(QRect(190, 130, 71, 61))
        self.btn_RXp.setFont(font2)
        self.btn_RXp.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_RXm = QPushButton(self.frame_tcp_orientation)
        self.btn_RXm.setObjectName(u"btn_RXm")
        self.btn_RXm.setGeometry(QRect(10, 130, 71, 61))
        self.btn_RXm.setFont(font2)
        self.btn_RXm.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_RZm = QPushButton(self.frame_tcp_orientation)
        self.btn_RZm.setObjectName(u"btn_RZm")
        self.btn_RZm.setGeometry(QRect(10, 50, 71, 61))
        self.btn_RZm.setFont(font2)
        self.btn_RZm.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_RZm.setIconSize(QSize(50, 50))
        self.btn_RZp = QPushButton(self.frame_tcp_orientation)
        self.btn_RZp.setObjectName(u"btn_RZp")
        self.btn_RZp.setGeometry(QRect(190, 50, 71, 61))
        self.btn_RZp.setFont(font2)
        self.btn_RZp.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label_step_degrees = QLabel(self.frame_tcp_orientation)
        self.label_step_degrees.setObjectName(u"label_step_degrees")
        self.label_step_degrees.setGeometry(QRect(11, 260, 251, 21))
        self.label_step_degrees.setFont(font1)
        self.lineEdit_step_degrees_1 = QLineEdit(self.frame_tcp_orientation)
        self.lineEdit_step_degrees_1.setObjectName(u"lineEdit_step_degrees_1")
        self.lineEdit_step_degrees_1.setGeometry(QRect(211, 280, 51, 22))
        self.lineEdit_step_degrees_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_step_degrees_1.setReadOnly(True)
        self.slider_step_degrees_1 = QSlider(self.frame_tcp_orientation)
        self.slider_step_degrees_1.setObjectName(u"slider_step_degrees_1")
        self.slider_step_degrees_1.setGeometry(QRect(10, 280, 191, 22))
        self.slider_step_degrees_1.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.slider_step_degrees_1.setMouseTracking(True)
        self.slider_step_degrees_1.setMinimum(1)
        self.slider_step_degrees_1.setMaximum(100)
        self.slider_step_degrees_1.setValue(1)
        self.slider_step_degrees_1.setOrientation(Qt.Orientation.Horizontal)
        self.slider_step_degrees_1.setInvertedAppearance(False)
        self.slider_step_degrees_1.setInvertedControls(False)
        self.frame_tcp_position = QFrame(self.tab_XYZ)
        self.frame_tcp_position.setObjectName(u"frame_tcp_position")
        self.frame_tcp_position.setEnabled(True)
        self.frame_tcp_position.setGeometry(QRect(10, 10, 271, 311))
        font4 = QFont()
        font4.setFamilies([u"Yu Gothic"])
        font4.setPointSize(12)
        font4.setBold(False)
        self.frame_tcp_position.setFont(font4)
        self.frame_tcp_position.setFrameShape(QFrame.Shape.Box)
        self.frame_tcp_position.setFrameShadow(QFrame.Shadow.Plain)
        self.frame_tcp_position.setLineWidth(2)
        self.frame_tcp_position.setMidLineWidth(0)
        self.btn_Ym = QPushButton(self.frame_tcp_position)
        self.btn_Ym.setObjectName(u"btn_Ym")
        self.btn_Ym.setGeometry(QRect(10, 130, 71, 61))
        self.btn_Ym.setFont(font2)
        self.btn_Ym.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label_tcp_position = QLabel(self.frame_tcp_position)
        self.label_tcp_position.setObjectName(u"label_tcp_position")
        self.label_tcp_position.setGeometry(QRect(10, 10, 231, 20))
        font5 = QFont()
        font5.setFamilies([u"Yu Gothic"])
        font5.setPointSize(12)
        font5.setBold(True)
        font5.setItalic(False)
        self.label_tcp_position.setFont(font5)
        self.btn_Yp = QPushButton(self.frame_tcp_position)
        self.btn_Yp.setObjectName(u"btn_Yp")
        self.btn_Yp.setGeometry(QRect(190, 130, 71, 61))
        self.btn_Yp.setFont(font2)
        self.btn_Yp.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Yp.setCheckable(False)
        self.btn_Yp.setFlat(False)
        self.btn_Xp = QPushButton(self.frame_tcp_position)
        self.btn_Xp.setObjectName(u"btn_Xp")
        self.btn_Xp.setGeometry(QRect(100, 180, 71, 61))
        self.btn_Xp.setFont(font2)
        self.btn_Xp.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Xm = QPushButton(self.frame_tcp_position)
        self.btn_Xm.setObjectName(u"btn_Xm")
        self.btn_Xm.setGeometry(QRect(100, 100, 71, 61))
        self.btn_Xm.setFont(font2)
        self.btn_Xm.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Zm = QPushButton(self.frame_tcp_position)
        self.btn_Zm.setObjectName(u"btn_Zm")
        self.btn_Zm.setEnabled(True)
        self.btn_Zm.setGeometry(QRect(10, 50, 71, 61))
        self.btn_Zm.setFont(font2)
        self.btn_Zm.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btn_Zm.setMouseTracking(False)
        self.btn_Zm.setTabletTracking(False)
        self.btn_Zm.setAutoFillBackground(False)
        self.btn_Zm.setIconSize(QSize(50, 50))
        self.btn_Zp = QPushButton(self.frame_tcp_position)
        self.btn_Zp.setObjectName(u"btn_Zp")
        self.btn_Zp.setGeometry(QRect(190, 50, 71, 61))
        self.btn_Zp.setFont(font2)
        self.btn_Zp.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label_step_mm = QLabel(self.frame_tcp_position)
        self.label_step_mm.setObjectName(u"label_step_mm")
        self.label_step_mm.setGeometry(QRect(10, 260, 251, 16))
        self.label_step_mm.setFont(font1)
        self.lineEdit_step_mm = QLineEdit(self.frame_tcp_position)
        self.lineEdit_step_mm.setObjectName(u"lineEdit_step_mm")
        self.lineEdit_step_mm.setGeometry(QRect(210, 280, 51, 22))
        self.lineEdit_step_mm.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_step_mm.setReadOnly(True)
        self.slider_step_mm = QSlider(self.frame_tcp_position)
        self.slider_step_mm.setObjectName(u"slider_step_mm")
        self.slider_step_mm.setGeometry(QRect(9, 280, 191, 22))
        self.slider_step_mm.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.slider_step_mm.setMouseTracking(True)
        self.slider_step_mm.setMinimum(1)
        self.slider_step_mm.setMaximum(100)
        self.slider_step_mm.setValue(1)
        self.slider_step_mm.setSliderPosition(1)
        self.slider_step_mm.setOrientation(Qt.Orientation.Horizontal)
        self.slider_step_mm.setInvertedAppearance(False)
        self.slider_step_mm.setInvertedControls(False)
        self.tabWidget.addTab(self.tab_XYZ, "")
        self.tab_Joints = QWidget()
        self.tab_Joints.setObjectName(u"tab_Joints")
        self.frame_joints_direction = QFrame(self.tab_Joints)
        self.frame_joints_direction.setObjectName(u"frame_joints_direction")
        self.frame_joints_direction.setGeometry(QRect(300, 10, 491, 421))
        self.frame_joints_direction.setFrameShape(QFrame.Shape.Box)
        self.frame_joints_direction.setFrameShadow(QFrame.Shadow.Plain)
        self.frame_joints_direction.setLineWidth(2)
        self.frame_joints_direction.setMidLineWidth(0)
        self.label_joints_direction = QLabel(self.frame_joints_direction)
        self.label_joints_direction.setObjectName(u"label_joints_direction")
        self.label_joints_direction.setGeometry(QRect(10, 10, 251, 20))
        self.label_joints_direction.setFont(font1)
        self.joints_picture = QLabel(self.frame_joints_direction)
        self.joints_picture.setObjectName(u"joints_picture")
        self.joints_picture.setGeometry(QRect(100, 30, 301, 381))
        self.joints_picture.setPixmap(QPixmap(u"rcc/joints_png.PNG"))
        self.joints_picture.setScaledContents(True)
        self.label_52 = QLabel(self.frame_joints_direction)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(190, 300, 15, 27))
        self.label_52.setFont(font4)
        self.label_53 = QLabel(self.frame_joints_direction)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(150, 210, 15, 27))
        self.label_54 = QLabel(self.frame_joints_direction)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(350, 130, 15, 27))
        self.label_55 = QLabel(self.frame_joints_direction)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(230, 20, 15, 27))
        self.label_56 = QLabel(self.frame_joints_direction)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(180, 40, 15, 27))
        self.label_57 = QLabel(self.frame_joints_direction)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(100, 100, 15, 27))
        self.joints_picture.raise_()
        self.label_joints_direction.raise_()
        self.label_53.raise_()
        self.label_54.raise_()
        self.label_55.raise_()
        self.label_56.raise_()
        self.label_57.raise_()
        self.label_52.raise_()
        self.frame_joints_position = QFrame(self.tab_Joints)
        self.frame_joints_position.setObjectName(u"frame_joints_position")
        self.frame_joints_position.setGeometry(QRect(300, 450, 491, 201))
        self.frame_joints_position.setFrameShape(QFrame.Shape.Box)
        self.frame_joints_position.setFrameShadow(QFrame.Shadow.Plain)
        self.frame_joints_position.setLineWidth(2)
        self.frame_joints_position.setMidLineWidth(0)
        self.label_tool_position_4 = QLabel(self.frame_joints_position)
        self.label_tool_position_4.setObjectName(u"label_tool_position_4")
        self.label_tool_position_4.setGeometry(QRect(10, 10, 251, 20))
        self.label_tool_position_4.setFont(font1)
        self.layoutWidget_4 = QWidget(self.frame_joints_position)
        self.layoutWidget_4.setObjectName(u"layoutWidget_4")
        self.layoutWidget_4.setGeometry(QRect(20, 40, 451, 141))
        self.gridLayout_4 = QGridLayout(self.layoutWidget_4)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_45 = QLabel(self.layoutWidget_4)
        self.label_45.setObjectName(u"label_45")

        self.gridLayout_4.addWidget(self.label_45, 0, 0, 1, 1)

        self.label_40 = QLabel(self.layoutWidget_4)
        self.label_40.setObjectName(u"label_40")

        self.gridLayout_4.addWidget(self.label_40, 0, 4, 1, 1)

        self.label_44 = QLabel(self.layoutWidget_4)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setEnabled(True)

        self.gridLayout_4.addWidget(self.label_44, 0, 2, 1, 1)

        self.label_51 = QLabel(self.layoutWidget_4)
        self.label_51.setObjectName(u"label_51")

        self.gridLayout_4.addWidget(self.label_51, 2, 4, 1, 1)

        self.label_46 = QLabel(self.layoutWidget_4)
        self.label_46.setObjectName(u"label_46")

        self.gridLayout_4.addWidget(self.label_46, 1, 6, 1, 1)

        self.lineEdit_J4 = QLineEdit(self.layoutWidget_4)
        self.lineEdit_J4.setObjectName(u"lineEdit_J4")
        self.lineEdit_J4.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_J4.setReadOnly(True)

        self.gridLayout_4.addWidget(self.lineEdit_J4, 0, 5, 1, 1)

        self.label_47 = QLabel(self.layoutWidget_4)
        self.label_47.setObjectName(u"label_47")

        self.gridLayout_4.addWidget(self.label_47, 1, 4, 1, 1)

        self.lineEdit_J3 = QLineEdit(self.layoutWidget_4)
        self.lineEdit_J3.setObjectName(u"lineEdit_J3")
        self.lineEdit_J3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_J3.setReadOnly(True)

        self.gridLayout_4.addWidget(self.lineEdit_J3, 2, 1, 1, 1)

        self.lineEdit_J2 = QLineEdit(self.layoutWidget_4)
        self.lineEdit_J2.setObjectName(u"lineEdit_J2")
        self.lineEdit_J2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_J2.setReadOnly(True)

        self.gridLayout_4.addWidget(self.lineEdit_J2, 1, 1, 1, 1)

        self.lineEdit_J1 = QLineEdit(self.layoutWidget_4)
        self.lineEdit_J1.setObjectName(u"lineEdit_J1")
        self.lineEdit_J1.setCursorPosition(3)
        self.lineEdit_J1.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_J1.setReadOnly(True)

        self.gridLayout_4.addWidget(self.lineEdit_J1, 0, 1, 1, 1)

        self.lineEdit_J6 = QLineEdit(self.layoutWidget_4)
        self.lineEdit_J6.setObjectName(u"lineEdit_J6")
        self.lineEdit_J6.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_J6.setReadOnly(True)

        self.gridLayout_4.addWidget(self.lineEdit_J6, 2, 5, 1, 1)

        self.label_50 = QLabel(self.layoutWidget_4)
        self.label_50.setObjectName(u"label_50")

        self.gridLayout_4.addWidget(self.label_50, 1, 0, 1, 1)

        self.label_48 = QLabel(self.layoutWidget_4)
        self.label_48.setObjectName(u"label_48")

        self.gridLayout_4.addWidget(self.label_48, 2, 0, 1, 1)

        self.label_49 = QLabel(self.layoutWidget_4)
        self.label_49.setObjectName(u"label_49")

        self.gridLayout_4.addWidget(self.label_49, 2, 2, 1, 1)

        self.label_41 = QLabel(self.layoutWidget_4)
        self.label_41.setObjectName(u"label_41")

        self.gridLayout_4.addWidget(self.label_41, 2, 6, 1, 1)

        self.label_42 = QLabel(self.layoutWidget_4)
        self.label_42.setObjectName(u"label_42")

        self.gridLayout_4.addWidget(self.label_42, 1, 2, 1, 1)

        self.lineEdit_J5 = QLineEdit(self.layoutWidget_4)
        self.lineEdit_J5.setObjectName(u"lineEdit_J5")
        self.lineEdit_J5.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_J5.setReadOnly(True)

        self.gridLayout_4.addWidget(self.lineEdit_J5, 1, 5, 1, 1)

        self.label_43 = QLabel(self.layoutWidget_4)
        self.label_43.setObjectName(u"label_43")

        self.gridLayout_4.addWidget(self.label_43, 0, 6, 1, 1)

        self.horizontalSpacer_4 = QSpacerItem(13, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_4.addItem(self.horizontalSpacer_4, 0, 3, 1, 1)

        self.label_40.raise_()
        self.label_41.raise_()
        self.label_42.raise_()
        self.label_43.raise_()
        self.label_44.raise_()
        self.label_45.raise_()
        self.label_46.raise_()
        self.label_47.raise_()
        self.label_48.raise_()
        self.label_49.raise_()
        self.label_50.raise_()
        self.label_51.raise_()
        self.lineEdit_J2.raise_()
        self.lineEdit_J1.raise_()
        self.lineEdit_J6.raise_()
        self.lineEdit_J4.raise_()
        self.lineEdit_J3.raise_()
        self.lineEdit_J5.raise_()
        self.frame_joints_orientation = QFrame(self.tab_Joints)
        self.frame_joints_orientation.setObjectName(u"frame_joints_orientation")
        self.frame_joints_orientation.setGeometry(QRect(10, 10, 271, 641))
        self.frame_joints_orientation.setFrameShape(QFrame.Shape.Box)
        self.frame_joints_orientation.setFrameShadow(QFrame.Shadow.Plain)
        self.frame_joints_orientation.setLineWidth(2)
        self.frame_joints_orientation.setMidLineWidth(0)
        self.label_joints_orientation = QLabel(self.frame_joints_orientation)
        self.label_joints_orientation.setObjectName(u"label_joints_orientation")
        self.label_joints_orientation.setGeometry(QRect(10, 10, 251, 20))
        self.label_joints_orientation.setFont(font1)
        self.label_step_degrees_2 = QLabel(self.frame_joints_orientation)
        self.label_step_degrees_2.setObjectName(u"label_step_degrees_2")
        self.label_step_degrees_2.setGeometry(QRect(11, 590, 251, 21))
        self.label_step_degrees_2.setFont(font1)
        self.lineEdit_step_degrees_2 = QLineEdit(self.frame_joints_orientation)
        self.lineEdit_step_degrees_2.setObjectName(u"lineEdit_step_degrees_2")
        self.lineEdit_step_degrees_2.setGeometry(QRect(211, 610, 51, 22))
        self.lineEdit_step_degrees_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_step_degrees_2.setReadOnly(True)
        self.slider_step_degrees_2 = QSlider(self.frame_joints_orientation)
        self.slider_step_degrees_2.setObjectName(u"slider_step_degrees_2")
        self.slider_step_degrees_2.setGeometry(QRect(10, 610, 191, 22))
        self.slider_step_degrees_2.setMinimum(1)
        self.slider_step_degrees_2.setMaximum(100)
        self.slider_step_degrees_2.setValue(1)
        self.slider_step_degrees_2.setOrientation(Qt.Orientation.Horizontal)
        self.slider_step_degrees_2.setInvertedAppearance(False)
        self.slider_step_degrees_2.setInvertedControls(False)
        self.gridLayoutWidget = QWidget(self.frame_joints_orientation)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 40, 251, 541))
        self.btns_J = QGridLayout(self.gridLayoutWidget)
        self.btns_J.setObjectName(u"btns_J")
        self.btns_J.setContentsMargins(0, 0, 0, 0)
        self.btn_J3m = QPushButton(self.gridLayoutWidget)
        self.btn_J3m.setObjectName(u"btn_J3m")
        self.btn_J3m.setFont(font1)
        self.btn_J3m.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.btns_J.addWidget(self.btn_J3m, 2, 0, 1, 1)

        self.btn_J6p = QPushButton(self.gridLayoutWidget)
        self.btn_J6p.setObjectName(u"btn_J6p")
        self.btn_J6p.setFont(font1)
        self.btn_J6p.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.btns_J.addWidget(self.btn_J6p, 5, 1, 1, 1)

        self.btn_J4m = QPushButton(self.gridLayoutWidget)
        self.btn_J4m.setObjectName(u"btn_J4m")
        self.btn_J4m.setFont(font1)
        self.btn_J4m.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.btns_J.addWidget(self.btn_J4m, 3, 0, 1, 1)

        self.btn_J6m = QPushButton(self.gridLayoutWidget)
        self.btn_J6m.setObjectName(u"btn_J6m")
        self.btn_J6m.setFont(font1)
        self.btn_J6m.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.btns_J.addWidget(self.btn_J6m, 5, 0, 1, 1)

        self.btn_J5m = QPushButton(self.gridLayoutWidget)
        self.btn_J5m.setObjectName(u"btn_J5m")
        self.btn_J5m.setFont(font1)
        self.btn_J5m.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.btns_J.addWidget(self.btn_J5m, 4, 0, 1, 1)

        self.btn_J2m = QPushButton(self.gridLayoutWidget)
        self.btn_J2m.setObjectName(u"btn_J2m")
        self.btn_J2m.setFont(font1)
        self.btn_J2m.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.btns_J.addWidget(self.btn_J2m, 1, 0, 1, 1)

        self.btn_J4p = QPushButton(self.gridLayoutWidget)
        self.btn_J4p.setObjectName(u"btn_J4p")
        self.btn_J4p.setFont(font1)
        self.btn_J4p.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.btns_J.addWidget(self.btn_J4p, 3, 1, 1, 1)

        self.btn_J1m = QPushButton(self.gridLayoutWidget)
        self.btn_J1m.setObjectName(u"btn_J1m")
        self.btn_J1m.setFont(font1)
        self.btn_J1m.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.btns_J.addWidget(self.btn_J1m, 0, 0, 1, 1)

        self.btn_J5p = QPushButton(self.gridLayoutWidget)
        self.btn_J5p.setObjectName(u"btn_J5p")
        self.btn_J5p.setFont(font1)
        self.btn_J5p.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.btns_J.addWidget(self.btn_J5p, 4, 1, 1, 1)

        self.btn_J1p = QPushButton(self.gridLayoutWidget)
        self.btn_J1p.setObjectName(u"btn_J1p")
        self.btn_J1p.setFont(font1)
        self.btn_J1p.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.btns_J.addWidget(self.btn_J1p, 0, 1, 1, 1)

        self.btn_J2p = QPushButton(self.gridLayoutWidget)
        self.btn_J2p.setObjectName(u"btn_J2p")
        self.btn_J2p.setFont(font1)
        self.btn_J2p.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.btns_J.addWidget(self.btn_J2p, 1, 1, 1, 1)

        self.btn_J3p = QPushButton(self.gridLayoutWidget)
        self.btn_J3p.setObjectName(u"btn_J3p")
        self.btn_J3p.setFont(font1)
        self.btn_J3p.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.btns_J.addWidget(self.btn_J3p, 2, 1, 1, 1)

        self.tabWidget.addTab(self.tab_Joints, "")
        self.btn_connect = QPushButton(self.centralwidget)
        self.btn_connect.setObjectName(u"btn_connect")
        self.btn_connect.setGeometry(QRect(10, 10, 291, 51))
        self.btn_connect.setFont(font3)
        self.btn_connect.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.btn_Yp.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Graphical User Interface | Mitsubishi RV-3SDB", None))
        self.label_socket_configuration.setText(QCoreApplication.translate("MainWindow", u"Socket Configuration", None))
        self.IP_value.setText(QCoreApplication.translate("MainWindow", u"172.16.0.4", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"IP:", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Port:", None))
        self.Port_value.setText(QCoreApplication.translate("MainWindow", u"10003", None))
        self.btn_set_socket.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.btn_reset_socket.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.label_tool_position.setText(QCoreApplication.translate("MainWindow", u"Tool Position", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"RX", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"mm", None))
        self.lineEdit_RY.setText(QCoreApplication.translate("MainWindow", u"---", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"mm", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.lineEdit_X.setText(QCoreApplication.translate("MainWindow", u"---", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.lineEdit_RZ.setText(QCoreApplication.translate("MainWindow", u"---", None))
        self.lineEdit_Z.setText(QCoreApplication.translate("MainWindow", u"---", None))
        self.lineEdit_RX.setText(QCoreApplication.translate("MainWindow", u"---", None))
        self.lineEdit_Y.setText(QCoreApplication.translate("MainWindow", u"---", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"RY", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"mm", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"RZ", None))
        self.label_axis_picture.setText(QCoreApplication.translate("MainWindow", u"Axis Direction", None))
        self.axis_picture.setText("")
        self.btn_RYm.setText(QCoreApplication.translate("MainWindow", u"RY-", None))
        self.label_tcp_orientation.setText(QCoreApplication.translate("MainWindow", u"TCP Orientation", None))
        self.btn_RYp.setText(QCoreApplication.translate("MainWindow", u"RY+", None))
        self.btn_RXp.setText(QCoreApplication.translate("MainWindow", u"RX+", None))
        self.btn_RXm.setText(QCoreApplication.translate("MainWindow", u"RX-", None))
        self.btn_RZm.setText(QCoreApplication.translate("MainWindow", u"RZ-", None))
        self.btn_RZp.setText(QCoreApplication.translate("MainWindow", u"RZ+", None))
        self.label_step_degrees.setText(QCoreApplication.translate("MainWindow", u"Step (degrees, \u00b0)", None))
        self.lineEdit_step_degrees_1.setText(QCoreApplication.translate("MainWindow", u"0.1", None))
        self.btn_Ym.setText(QCoreApplication.translate("MainWindow", u"Y-", None))
        self.label_tcp_position.setText(QCoreApplication.translate("MainWindow", u"TCP Position", None))
        self.btn_Yp.setText(QCoreApplication.translate("MainWindow", u"Y+", None))
        self.btn_Xp.setText(QCoreApplication.translate("MainWindow", u"X+", None))
        self.btn_Xm.setText(QCoreApplication.translate("MainWindow", u"X-", None))
        self.btn_Zm.setText(QCoreApplication.translate("MainWindow", u"Z-", None))
        self.btn_Zp.setText(QCoreApplication.translate("MainWindow", u"Z+", None))
        self.label_step_mm.setText(QCoreApplication.translate("MainWindow", u"Step (mm)", None))
        self.lineEdit_step_mm.setText(QCoreApplication.translate("MainWindow", u"0.1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_XYZ), QCoreApplication.translate("MainWindow", u"XYZ", None))
        self.label_joints_direction.setText(QCoreApplication.translate("MainWindow", u"Joints Direction", None))
        self.joints_picture.setText("")
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"J1", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"J2", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"J3", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"J4", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"J5", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"J6", None))
        self.label_tool_position_4.setText(QCoreApplication.translate("MainWindow", u"Joints Position", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"J1", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"J4", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"J6", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.lineEdit_J4.setText(QCoreApplication.translate("MainWindow", u"---", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"J5", None))
        self.lineEdit_J3.setText(QCoreApplication.translate("MainWindow", u"---", None))
        self.lineEdit_J2.setText(QCoreApplication.translate("MainWindow", u"---", None))
        self.lineEdit_J1.setText(QCoreApplication.translate("MainWindow", u"---", None))
        self.lineEdit_J6.setText(QCoreApplication.translate("MainWindow", u"---", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"J2", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"J3", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.lineEdit_J5.setText(QCoreApplication.translate("MainWindow", u"---", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.label_joints_orientation.setText(QCoreApplication.translate("MainWindow", u"Joints Orientation", None))
        self.label_step_degrees_2.setText(QCoreApplication.translate("MainWindow", u"Step (degrees, \u00b0)", None))
        self.lineEdit_step_degrees_2.setText(QCoreApplication.translate("MainWindow", u"0.1", None))
        self.btn_J3m.setText(QCoreApplication.translate("MainWindow", u"J3-", None))
        self.btn_J6p.setText(QCoreApplication.translate("MainWindow", u"J6+", None))
        self.btn_J4m.setText(QCoreApplication.translate("MainWindow", u"J4-", None))
        self.btn_J6m.setText(QCoreApplication.translate("MainWindow", u"J6-", None))
        self.btn_J5m.setText(QCoreApplication.translate("MainWindow", u"J5-", None))
        self.btn_J2m.setText(QCoreApplication.translate("MainWindow", u"J2-", None))
        self.btn_J4p.setText(QCoreApplication.translate("MainWindow", u"J4+", None))
        self.btn_J1m.setText(QCoreApplication.translate("MainWindow", u"J1-", None))
        self.btn_J5p.setText(QCoreApplication.translate("MainWindow", u"J5+", None))
        self.btn_J1p.setText(QCoreApplication.translate("MainWindow", u"J1+", None))
        self.btn_J2p.setText(QCoreApplication.translate("MainWindow", u"J2+", None))
        self.btn_J3p.setText(QCoreApplication.translate("MainWindow", u"J3+", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Joints), QCoreApplication.translate("MainWindow", u"Joints", None))
        self.btn_connect.setText(QCoreApplication.translate("MainWindow", u"CONNECT", None))
    # retranslateUi

